import Head from 'next/head';
import React, { FC } from 'react';
import { Navbar } from '../Navbar';
import styles from './MainLayout.module.css';

interface Props {
  children: React.ReactNode
}

const MainLayout = ({children}: Props) => {

  return (
    <>
      <Head>
        <title>Curso Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main className={styles.main}>
        {children}
      </main>
    </>
  )
}

export default MainLayout;